### ISSUE TITLE
Error when first calling `meeshkan setup`

### ISSUE THREAD

**Issue by idantene** [Meeshkan/meeshkan-client#161]
`FileNotFoundError: Create file /home/idan/.meeshkan/credentials first.`

**Comment by ksaaskil** [comment]
Is this a critical bug that will prevent any new user from setting up the client as instructed?

**Comment by ksaaskil** [comment]
Seems to also affect `master`, I assume it originates from [here](https://github.com/Meeshkan/meeshkan-client/blob/master/meeshkan/core/config.py#L87).

**Comment by idantene** [comment]
Resolved in #162 , closing.
