### ISSUE TITLE
Jupyter Notebook Integration

### ISSUE THREAD

**Issue by idantene** [Meeshkan/meeshkan-client#95]
Add support for Jupyter Notebook via calls e.g. `init`, `run` (takes a method, passes namespace?), etc.

**Comment by ksaaskil** [comment]
`meeshkan.init(token=...)`, `meeshkan.start()`, `meeshkan.stop()`, and `meeshkan.restart()` will be available in 0.1.4. I think any new features implementing job scheduling from Jupyter notebook could have a new more specific issue opened, so closing this.
